version: '3.8'

services:
  backend:
    build: ./magic-sandbox-back
    ports:
      - "8000:8000"

  frontend:
    build: ./magic-sandbox-front
    ports:
      - "5000:80"
    depends_on:
      - backend
