name: Build and push docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Backend Dependencies
      run: |
        cd magic-sandbox-back
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Backend Tests
      run: |
        cd magic-sandbox-back
        pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Backend Docker Image
      run: |
        cd magic-sandbox-back
        docker build -t samuelholmes/magic-sandbox-back:latest .
        docker push samuelholmes/magic-sandbox-back:latest
        cd ..

  frontend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Frontend Dependencies
      run: |
        cd magic-sandbox-front
        npm install
        cd ..

    - name: Build Frontend Project
      run: |
        cd magic-sandbox-front
        npm run build
        cd ..

    - name: Build and Push Frontend Docker Image
      run: |
        cd magic-sandbox-front
        docker build -t samuelholmes/magic-sandbox-front:latest .
        docker push samuelholmes/magic-sandbox-front:latest

