name: Build and push docker images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Backend Dependencies
      run: |
        cd magic-sandbox-back
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Backend Tests with coverage
      run: |
        cd magic-sandbox-back
        pytest --cov=src tests/

  build-push-backend-image:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Backend Docker Image
      run: |
        cd magic-sandbox-back
        docker build -t samuelholmes/magic-sandbox-back:latest .
        docker push samuelholmes/magic-sandbox-back:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Frontend Dependencies
      run: |
        cd magic-sandbox-front
        npm install

    - name: Build Frontend Project
      run: |
        cd magic-sandbox-front
        npm run build

    - name: Upload Build Artifacts #allow to use it on a different job
      uses: actions/upload-artifact@v2
      with:
        name: frontend-build
        path: magic-sandbox-front/build/
        retention-days: 1

  build-push-frontend-image:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Build Artifacts #recover the artifact built on last job
      uses: actions/download-artifact@v2
      with:
        name: frontend-build
        path: magic-sandbox-front/build/

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        cd magic-sandbox-front
        docker build -t samuelholmes/magic-sandbox-front:latest .
        docker push samuelholmes/magic-sandbox-front:latest
